### ISSUE TITLE
minOut should be enforced by the module contract

### ISSUE THREAD

**Issue by fleupold** [cowdao-grants/cow-fee#18]
MinOut amount is currently enforced by the script, ie it doesn't place any orders for which the quote doesn't return at least minOut tokens. The currency is determined in buyTokens, which itself is configured and enforced by the module contract.

I think it would be more coherent if the minOut amount was also configured and enforced on the contract. This would avoid possible grieving attacks.

**Comment by meetmangukiya** [comment]
What do you mean enforce on contract level? minOut for the order will be set in the order and will be enforced by the settlement contract already.

**Comment by fleupold** [comment]
The main attack vector of this component is the keeper account PK leaking and going into malicious hands. 

The module currently enforces that funds cannot be stolen (ie recipient and buy token are fixed by whoever deployed and enabled the module).
However there is still a grieving attack vector where orders are made so small that 99% of the value is eaten up by fees. If the min out amount was enforced in the module (and we would revert if an order was placed with a minBuyAmount < that value) then this attack would no longer be possible (as you are unable to place limit orders which are willing to buy small amounts).

I hope this makes sense.

**Comment by meetmangukiya** [comment]
Okay, yeah I understand now
